-- MAITRI Supabase starter schema
-- Run this in the Supabase SQL Editor after creating your project.
create table if not exists public.project_settings (
  id bigint generated by default as identity primary key,
  name text not null,
  tagline text,
  title text,
  description text,
  updated_at timestamptz default now()
);
create table if not exists public.objectives (
  id bigint generated by default as identity primary key,
  objective_no integer not null,
  title text not null,
  description text not null,
  sort_order integer default 0
);
create table if not exists public.methodology (
  id bigint generated by default as identity primary key,
  phase_no integer not null,
  title text not null,
  description text not null,
  sort_order integer default 0
);
create table if not exists public.research_questions (
  id bigint generated by default as identity primary key,
  question_no integer not null,
  question text not null,
  sort_order integer default 0
);
create table if not exists public.researchers (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  image_url text,
  profile_url text,
  research_areas text[] default '{}',
  sort_order integer default 0
);
create table if not exists public.roadmap (
  id bigint generated by default as identity primary key,
  year_label text not null,
  theme text,
  items text[] default '{}',
  sort_order integer default 0
);

-- Enable RLS before connecting a public frontend.
alter table public.project_settings enable row level security;
alter table public.objectives enable row level security;
alter table public.methodology enable row level security;
alter table public.research_questions enable row level security;
alter table public.researchers enable row level security;
alter table public.roadmap enable row level security;

-- Public website: read-only access. Admin write policies should be added only
-- after Supabase Auth is configured for authorised project administrators.
create policy "public can read project settings" on public.project_settings for select using (true);
create policy "public can read objectives" on public.objectives for select using (true);
create policy "public can read methodology" on public.methodology for select using (true);
create policy "public can read research questions" on public.research_questions for select using (true);
create policy "public can read researchers" on public.researchers for select using (true);
create policy "public can read roadmap" on public.roadmap for select using (true);
